### ISSUE TITLE
Functionality and usage example

### ISSUE THREAD

**Issue by Antonio95** [scroll-tech/poseidon-circuit#26]
My team (@mmagician) and I have a couple of questions on the functionality of the crate:

1. Are we correct in thinking that the crate implements the following two distinct functionalities?
 - Compute/verify a list of pairs (x, y), where y is claimed to be the Poseidon hash of x. This seems to be the idea of `PoseidonHashTable` and its containing struct `SpongeChip`.
 - Compute/verify a number of (possibly interleaved?) function calls to absorb and squeeze elements. This seems to be in line with the `Sponge` struct.
2. Why does the `input` field of the `PoseidonHashTable` struct consist of a list of pairs? In other words, what are this pairs meant to represent?
3. We are struggling to produce a simple running example where the `Sponge` structure is embedded in a circuit, absorbs a few elements and then squeezes some. We have made progress in digging through the generics of it, but it would be extremely useful to see a working example written by someone who knows the ins and outs of the crate.

**Comment by noel2004** [comment]
> My team (@mmagician) and I have a couple of questions on the functionality of the crate:
> 
> 1. Are we correct in thinking that the crate implements the following two distinct functionalities?
> 
> * Compute/verify a list of pairs (x, y), where y is claimed to be the Poseidon hash of x. This seems to be the idea of `PoseidonHashTable` and its containing struct `SpongeChip`.

Yes. but it should be pairs (x, y) and its poseidon hash H(x, y)?

> * Compute/verify a number of (possibly interleaved?) function calls to absorb and squeeze elements. This seems to be in line with the `Sponge` struct.

To verify a list of inputs (each is a pair) with arbitary length, no interleaved.

I think it is not function calls. Or something I haven't caught?

> 
> 2. Why does the `input` field of the `PoseidonHashTable` struct consist of a list of pairs? In other words, what are this pairs meant to represent?

You can permute an array of fields with specified number. We select array of 3 fields (2 as input) since it fit our mpt -circuit's scheme best.

> 3. We are struggling to produce a simple running example where the `Sponge` structure is embedded in a circuit, absorbs a few elements and then squeezes some. We have made progress in digging through the generics of it, but it would be extremely useful to see a working example written by someone who knows the ins and outs of the crate.

We have implied the [`SpongeChip`](https://github.com/scroll-tech/poseidon-circuit/blob/9fff0c0a4d6d98c03e952c03e2b3810c870d61a2/src/hash.rs#L389) which has applied our poseidon scheme. And the circuit with poseidon table seems work just as your descirption (absorbs elements and squeeze one field as output). If it is not fit to your expection, you can tailor the permutation (with [the basic pow5 scheme](https://github.com/scroll-tech/poseidon-circuit/blob/9fff0c0a4d6d98c03e952c03e2b3810c870d61a2/src/poseidon/pow5.rs#L37) or ['septidon' which is an optimized one](https://github.com/scroll-tech/poseidon-circuit/blob/9fff0c0a4d6d98c03e952c03e2b3810c870d61a2/src/poseidon/septidon/instruction.rs#L15)) circuit and wrap it into yourself's sponge scheme.

**Comment by Antonio95** [comment]
Thank you very much for your answer. The bits about the input being pairs of elements (and the output the hashes of each pair) is now clear. I might keep working to get a running example within my broader code.
